### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by alishasonawalla**
This PR fixes the broken license link reported in issue https://github.com/nyu-ossd-s19/mood/issues/10.

### CODE REVIEW

**Comment by alishasonawalla** [comment]
This PR also fixes the broken contributing link reported in issue https://github.com/nyu-ossd-s19/mood/issues/9

**Review by candacej97 — CHANGES_REQUESTED** [review]
Thanks for the catch!
Can you use relative linking for this link and the license link change you made?

**Comment by alishasonawalla** [comment]
@candacej97 Done :)

**Comment by candacej97** [comment]
Thanks

**Review by candacej97 — COMMENTED** [review]
Looks good!

**Pull request merged**
